import "@repo/theme-quartz/css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@repo/components-react/common/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UI demo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
