import { toKebabCase } from "@repo/utils";

/**
 * Converts design token data to a writable CSS definition
 * TODO: add types from a global type package
 * @param designTokens
 */
export const covertDesignTokensToCss = (designTokens: any) => {
  let data = "/* Generated by @repo/build-tools */\n";
  data =
    data + "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n";
  data = data + "@layer base {\n  :root {\n";
  Object.entries(designTokens.root).map(([key, hsl]) => {
    data = data + `    --${toKebabCase(key)}: ${hsl};\n`;
  });
  data = data + "  }\n  .dark {\n";
  Object.entries(designTokens.dark).map(([key, hsl]) => {
    data = data + `    --${toKebabCase(key)}: ${hsl};\n`;
  });
  data = data + "  }\n}\n\n";
  return data;
};
